version: '4'
services:
  sdp_front:
    image: registry.cn-hangzhou.aliyuncs.com/sutao_aliyun/chitu-sdp-front:1.0
    container_name: sdp-front
    restart: always
    ports:
      - 38081:80
    depends_on:
      - sdp_backend
  sdp_backend:
    image: registry.cn-hangzhou.aliyuncs.com/sutao_aliyun/chitu-sdp-backend:2.0
    container_name: sdp-backend
    restart: always
    depends_on:
      - sdp_submit114
      - sdp_submit115
      - nacos
      - redis
      - mysql
    extra_hosts:
      - "hadoop01:172.16.81.161"
      - "hadoop02:172.16.81.162"
      - "hadoop03:172.16.81.163"
    expose:
      - 12222
    command: /bin/sh -c "/app/sh/bigdata-services start chitu-provider-1.0.0-SNAPSHOT 12222"
  sdp_submit114:
    image: registry.cn-hangzhou.aliyuncs.com/sutao_aliyun/chitu-sdp-backend:2.0
    container_name: sdp-submit114
    restart: always
    expose:
      - 12282
    extra_hosts:
      - "hadoop01:172.16.81.161"
      - "hadoop02:172.16.81.162"
      - "hadoop03:172.16.81.163"
    command: /bin/sh -c "sh /app/sh/bigdata-services start chitu-flink-submit-114-1.0.0-SNAPSHOT 12282"
  sdp_submit115:
    image: registry.cn-hangzhou.aliyuncs.com/sutao_aliyun/chitu-sdp-backend:2.0
    container_name: sdp-submit115
    restart: always
    expose:
      - 12283
    extra_hosts:
      - "hadoop01:172.16.81.161"
      - "hadoop02:172.16.81.162"
      - "hadoop03:172.16.81.163"
    command: /bin/sh -c "sh /app/sh/bigdata-services start chitu-flink-submit-115-1.0.0-SNAPSHOT 12283"
  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "29090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 30004:3000
    restart: on-failure
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    user: root
    restart: always
    ports:
      - "9091:9091"
  redis:
    restart: always
    image: redis
    container_name: chitu-redis
    ports:
      - 6379:6379
    command: redis-server
  mysql:
    container_name: chitu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'chitu'
      MYSQL_PASS: '123456'
    image: mysql:5.7.28
    restart: always
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"

  zookeeper:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    #ports:
    #  - 32181:2181
    expose:
      - 2181
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh zookeeper"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-jn-0:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-jn-0
    hostname: hadoop-hdfs-jn-0
    restart: always
    depends_on:
      - zookeeper
    expose:
      - 8485
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-jn"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8485 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-jn-1:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-jn-1
    hostname: hadoop-hdfs-jn-1
    restart: always
    depends_on:
      - hadoop-hdfs-jn-0
    expose:
      - 8485
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-jn"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8485 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-jn-2:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-jn-2
    hostname: hadoop-hdfs-jn-2
    restart: always
    depends_on:
      - hadoop-hdfs-jn-1
    expose:
      - 8485
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-jn"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8485 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-nn-0:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-nn-0
    hostname: hadoop-hdfs-nn-0
    restart: always
    depends_on:
      - hadoop-hdfs-jn-2
    ports:
      - 30870:9870
    expose:
      - 8020
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-nn 'nn0'"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :9870 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-nn-1:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-nn-1
    hostname: hadoop-hdfs-nn-1
    restart: always
    depends_on:
      - hadoop-hdfs-nn-0
    ports:
      - 30871:9870
    expose:
      - 8020
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-nn 'nn1'"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :9870 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-dn-0:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-dn-0
    hostname: hadoop-hdfs-dn-0
    restart: always
    depends_on:
      - hadoop-hdfs-nn-1
    expose:
      - 9866
    ports:
      - 9864
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-dn"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :9866 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-dn-1:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-dn-1
    hostname: hadoop-hdfs-dn-1
    restart: always
    depends_on:
      - hadoop-hdfs-dn-0
    expose:
      - 9866
    ports:
      - 9864
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-dn"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :9866 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-hdfs-dn-2:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-hdfs-dn-2
    hostname: hadoop-hdfs-dn-2
    restart: always
    depends_on:
      - hadoop-hdfs-dn-1
    expose:
      - 9866
    ports:
      - 9864
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-hdfs-dn"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :9866 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-yarn-rm-0:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-yarn-rm-0
    hostname: hadoop-yarn-rm-0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 30088:8088
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-yarn-rm"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8088 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-yarn-rm-1:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-yarn-rm-1
    hostname: hadoop-yarn-rm-1
    restart: always
    depends_on:
      - hadoop-yarn-rm-0
    ports:
      - 30089:8088
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-yarn-rm"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8088 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-yarn-nm-0:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-yarn-nm-0
    hostname: hadoop-yarn-nm-0
    restart: always
    depends_on:
      - hadoop-yarn-rm-1
    expose:
      - 8042
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-yarn-nm"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8042 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-yarn-nm-1:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-yarn-nm-1
    hostname: hadoop-yarn-nm-1
    restart: always
    depends_on:
      - hadoop-yarn-nm-0
    expose:
      - 8042
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-yarn-nm"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8042 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-yarn-nm-2:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-yarn-nm-2
    hostname: hadoop-yarn-nm-2
    restart: always
    depends_on:
      - hadoop-yarn-nm-1
    expose:
      - 8042
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-yarn-nm"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :8042 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  hadoop-proxyserver:
    image: chitu-open-hadoop:3.1.1
    user: "9999:9999"
    container_name: hadoop-proxyserver
    hostname: hadoop-proxyserver
    restart: always
    depends_on:
      - hadoop-yarn-nm-2
    ports:
      - 30111:9111
    command: /bin/sh -c "sh /opt/apache/bootstrap.sh hadoop-proxyserver"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tnlp|grep :9111 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

